'use client'

// import type { Metadata } from "next";
import "./globals.css";
import { Inter } from "next/font/google";
import { AuthProvider } from "../context/AuthContext";
import { Providers } from "../context/providers";
import ProtectedLayout from "./protected/ProtectedLayout";
import { usePathname } from "next/navigation";

const inter = Inter({ subsets: ["latin"] })
// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname()
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <Providers>
          <AuthProvider>
            {pathname === "/login" || pathname === "/register" ? (
              children
            ) : (
              <ProtectedLayout>{children}</ProtectedLayout>
            )}
          </AuthProvider>
        </Providers>
      </body>
    </html>
  );
}