'use client'

// import type { Metadata } from "next";
import "./globals.css";
import { Inter } from "next/font/google";
import { AuthProvider } from "../context/AuthContext";
import { AppThemeProvider } from "../context/AppThemeProvider";
import ProtectedLayout from "./protected/ProtectedLayout";
import { usePathname } from "next/navigation";

const inter = Inter({ subsets: ["latin"] })
// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname()
  const isAuthRoute = pathname === "/login" || pathname === "/register"

  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.className} ${isAuthRoute ? "" : "dark"}`}>
        <AuthProvider>
          <AppThemeProvider>
            {isAuthRoute ? (
              children
            ) : (
              <ProtectedLayout>{children}</ProtectedLayout>
            )}
          </AppThemeProvider>
        </AuthProvider>
      </body>
    </html >
  );
}